version: "3"
services:
  # mysql:
  #   image: mysql:5.7.22
  #   container_name: get_db
  #   ports:
  #     - 33070:3306
  #   environment:
  #     MYSQL_DATABASE: get_db
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./data:/var/lib/mysql

  php:
    image: ocpp_simulator_app
    container_name: ocpp_simulator_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    # depends_on:
    #   - mysql
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      APP_ENV: local

  nginx:
    image: nginx:alpine
    container_name: ocpp_simulator_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
      - 8086:80
