version: "3"
services:
  app:
    image: ocpp_simulator_app
    container_name: ocpp_simulator_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: unless-stopped
    environment:
      APP_ENV: local

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: ocpp_simulator_nginx
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/ca-certificates
    links:
      - app
    ports:
      - 8086:80
